#!/usr/bin/env python3

import os, platform, subprocess, sys
from pathlib import Path

script_path = os.path.dirname(os.path.realpath(__file__))

if platform.system() == "Linux":
    encoding = "utf-8"
    project_path = "/".join(script_path.split('/')[:-1])
    dfu_util_path = project_path + "/.micromamba/dfu-util-be49612-binaries/linux-amd64/dfu-util"
elif platform.system() == "Windows":
    from subprocess import CREATE_NO_WINDOW
    encoding = "cp437"
    project_path = "\\".join(script_path.split('\\')[:-1])
    dfu_util_path = project_path + "\\.micromamba\\dfu-util-be49612-binaries\\win64\\dfu-util.exe"

    output = subprocess.check_output(["pnputil", "/enum-drivers"], creationflags=CREATE_NO_WINDOW).decode(encoding)
    if "stm32bootloader.inf" in output or "USB\VID_0483&PID_DF11 (libwdi autogenerated)" in output:
        print("STM32 Driver found")
    else:
        print("STM32bootloader Driver is missing. Run 'script\install_stm32_bootloader_driver.bat' to install.")
        exit(1)
else:
    sys.exit("Error: Not supported on this operating system")

if not Path(dfu_util_path).exists():
    sys.exit(f"Error: Expected dfu-util binaries at {dfu_util_path}")


def main():
    HELP = "Set the path to the binary to be flashed on the device as argument.\r\n" + \
       " Note: .elf files path will be replaced by .bin path\r\n" + \
       " ex: `python dfu-util.py <path_to_bin.elf>`"

    # If no options are given, print Help message
    if len(sys.argv) == 1:
        print(HELP)
        return

    binary_path = sys.argv[1]

    # Change the file path to a .bin file (vscode task will pass a .elf).
    file_path = binary_path
    filename = file_path.split(".")
    bin_path = f"{'.'.join(filename[:-1])}.bin"

    args = (f"{dfu_util_path}", "-a0", "-i0", "-s0x08000000:mass-erase:force:fast:leave", f"-D{bin_path}")

    with subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as p:
        while True:
            text = p.stdout.read1().decode(encoding)
            print(text, end='', flush=True)
            if p.poll() is not None:
                break

        errors = p.stderr.read1().decode(encoding).split('\n')
        for error in errors:
            if "No DFU capable USB device available" in error:
                # Other errors are filtered out since there were errors messages on leave.
                print(error + "\r\n  => Make sure USB DFU Drivers are installed")

if __name__ == '__main__':
    main()
